### ISSUE TITLE
Feedback: First Challenge Submission

### ISSUE THREAD

**Issue by anselb** [nsafai/Data-Structures#1]
- There was a bug that the tests caught for find_all_indexes, but I let it go because its a super quick fix for an edge case. Make sure everything you return from that function has a consistent type.
- Your encode and decode functions are short and sweet, which I think is good. One thing I would like to nitpick is that you could have used the variables quotient and remainder for q and r, considering you already wrote it out twice in the comments. It's all good though because it isn't used in a large scope, and you mention it twice in the comments.
- All your comments are great, and very helpful. One place that I thought could use a good explanation was for line 26 in bases.py. A couple things go on there, and people unfamiliar with decoding numbers might not understand.

**Comment by nsafai** [comment]
- [x] fixed find_all_index
- [x] renamed q and r to quotient and remainder :) why not! you're right.
- [x] added comment
>"""Encode given number in base 10 to digits in given base.
>For example, turn a decimal (0-9) number '4' into binary (0-1) number '100'
