### ISSUE TITLE
Feedback: Second Challenge Submission

### ISSUE THREAD

**Issue by anselb** [nsafai/Data-Structures#2]
- Nice work on your stack and queue methods. I don't think there is anything I would change, and your complexity annotations all seem to be correct.
- For your set, I recommend moving the items argument ahead of the size argument when initializing each structure. I think people are more likely to initialize those structures with items then they are to initialize it with a size, and I think it's possible to initialize the structure with a good size based on the length of the input items.
- Your set tests are fine the way they currently are, but you might consider varying the input to use integers or muli-character strings, as I have already seen this break someone's code. I would also like to see more testing of the size property.

**Comment by nsafai** [comment]
Thanks for the feedback and suggestions @anselb ! Addressed all your feedback in this commit: 
https://github.com/nsafai/Data-Structures/commit/06dad63348828626e2a2f8678c62a5b4dd839cd4
